use_frameworks!

target 'RACSendProgress_Example', :exclusive=> true do
  pod 'RACSendProgress', :path => '../'

end

target 'RACSendProgress_Tests', :exclusive=> true do
  pod 'RACSendProgress', :path => '../'

  pod 'Kiwi'
end
